### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by LeonPaterr** [soft-nougat/sogeti_qaif#6]
- Hyperlinks to libraries of mentioned packages
- 'Data Understading' is spelled wrong in the expandable of the bias-tabular example
- Perhaps add some spacing between the keyword-section and the data understanding in the technical examples. Alternatively have a frame around them similar to the expendables

**Comment by soft-nougat** [comment]
Done 🙂

**Comment by soft-nougat** [comment]
Done 🙂
